export const GET_ALL_NEWS_START = 'GET_ALL_NEWS_START';
export const GET_ALL_NEWS_SUCCESS = 'GET_ALL_NEWS_SUCCESS';
export const GET_ALL_NEWS_ERROR = 'GET_ALL_NEWS_ERROR';

export const LOAD_MORE_NEWS_START = 'LOAD_MORE_NEWS_START';
export const LOAD_MORE_NEWS_SUCCESS = 'LOAD_MORE_NEWS_SUCCESS';
export const LOAD_MORE_NEWS_ERROR = 'LOAD_MORE_NEWS_ERROR';

export const GET_SINGLE_NEWS_START = 'GET_SINGLE_NEWS_START';
export const GET_SINGLE_NEWS_SUCCESS = 'GET_SINGLE_NEWS_SUCCESS';
export const GET_SINGLE_NEWS_ERROR = 'GET_SINGLE_NEWS_ERROR';

export const GET_CATEGORIES_START = 'GET_CATEGORIES_START';
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
export const GET_CATEGORIES_ERROR = 'GET_CATEGORIES_ERROR';

export const GET_NEWS_BY_CATEGORY_START = 'GET_NEWS_BY_CATEGORY_START';
export const GET_NEWS_BY_CATEGORY_SUCCESS = 'GET_NEWS_BY_CATEGORY_SUCCESS';
export const GET_NEWS_BY_CATEGORY_ERROR = 'GET_NEWS_BY_CATEGORY_ERROR';

export const LOAD_MORE_NEWS_BY_CATEGORY_START =
  'LOAD_MORE_NEWS_BY_CATEGORY_START';
export const LOAD_MORE_NEWS_BY_CATEGORY_SUCCESS =
  'LOAD_MORE_NEWS_BY_CATEGORY_SUCCESS';
export const LOAD_MORE_NEWS_BY_CATEGORY_ERROR =
  'LOAD_MORE_NEWS_BY_CATEGORY_ERROR';

export const SEARCH_NEWS_START = 'SEARCH_NEWS_START';
export const SEARCH_NEWS_SUCCESS = 'SEARCH_NEWS_SUCCESS';
export const SEARCH_NEWS_ERROR = 'SEARCH_NEWS_ERROR';

export const SEARCH_MORE_NEWS_START = 'SEARCH_MORE_NEWS_START';
export const SEARCH_MORE_NEWS_SUCCESS = 'SEARCH_MORE_NEWS_SUCCESS';
export const SEARCH_MORE_NEWS_ERROR = 'SEARCH_MORE_NEWS_ERROR';

export const GET_RELATED_ARTICLES_START = 'GET_RELATED_ARTICLES_START';
export const GET_RELATED_ARTICLES_SUCCESS = 'GET_RELATED_ARTICLES_SUCCESS';
export const GET_RELATED_ARTICLES_ERROR = 'GET_RELATED_ARTICLES_ERROR';
