export const GET_ALL_MUSICS_START = 'GET_ALL_MUSICS_START';
export const GET_ALL_MUSICS_SUCCESS = 'GET_ALL_MUSICS_SUCCESS';
export const GET_ALL_MUSICS_ERROR = 'GET_ALL_MUSICS_ERROR';

export const GET_SINGLE_MUSIC_START = 'GET_SINGLE_MUSIC_START';
export const GET_SINGLE_MUSIC_SUCCESS = 'GET_SINGLE_MUSIC_SUCCESS';
export const GET_SINGLE_MUSIC_ERROR = 'GET_SINGLE_MUSIC_ERROR';

export const GET_MUSIC_CATEGORIES_START = 'GET_MUSIC_CATEGORIES_START';
export const GET_MUSIC_CATEGORIES_SUCCESS = 'GET_MUSIC_CATEGORIES_SUCCESS';
export const GET_MUSIC_CATEGORIES_ERROR = 'GET_MUSIC_CATEGORIES_ERROR';
