export const GET_ALL_TV_SHOWS_START = 'GET_ALL_TV_SHOWS_START';
export const GET_ALL_TV_SHOWS_SUCCESS = 'GET_ALL_TV_SHOWS_SUCCESS';
export const GET_ALL_TV_SHOWS_ERROR = 'GET_ALL_TV_SHOWS_ERROR';

export const GET_SINGLE_TV_SHOW_START = 'GET_SINGLE_TV_SHOW_START';
export const GET_SINGLE_TV_SHOW_SUCCESS = 'GET_SINGLE_TV_SHOW_SUCCESS';
export const GET_SINGLE_TV_SHOW_ERROR = 'GET_SINGLE_TV_SHOW_ERROR';

export const GET_TV_SHOW_CATEGORIES_START = 'GET_TV_SHOW_CATEGORIES_START';
export const GET_TV_SHOW_CATEGORIES_SUCCESS = 'GET_TV_SHOW_CATEGORIES_SUCCESS';
export const GET_TV_SHOW_CATEGORIES_ERROR = 'GET_TV_SHOW_CATEGORIES_ERROR';
