export const GET_RADIO_START = 'GET_RADIO_START';
export const GET_RADIO_SUCCESS = 'GET_RADIO_SUCCESS';
export const GET_RADIO_ERROR = 'GET_RADIO_ERROR';

export const GET_SINGLE_RADIO_START = 'GET_SINGLE_RADIO_START';
export const GET_SINGLE_RADIO_SUCCESS = 'GET_SINGLE_RADIO_SUCCESS';
export const GET_SINGLE_RADIO_ERROR = 'GET_SINGLE_RADIO_ERROR';

export const GET_RADIO_CATEGORIES_START = 'GET_RADIO_CATEGORIES_START';
export const GET_RADIO_CATEGORIES_SUCCESS = 'GET_RADIO_CATEGORIES_SUCCESS';
export const GET_RADIO_CATEGORIES_ERROR = 'GET_RADIO_CATEGORIES_ERROR';
